### ISSUE TITLE
Kerberos Support

### ISSUE THREAD

**Issue by enj** [alexbrainman/sspi#1]
@alexbrainman Could you point me to some documentation and/or links that could help me implement Kerberos support in Go on Windows using this library (something like https://github.com/alexbrainman/sspi/blob/master/ntlm/http_test.go)?

**Comment by alexbrainman** [comment]
> help me implement Kerberos support in Go on Windows

Microsoft provides different SSP providers

https://msdn.microsoft.com/en-us/library/windows/desktop/aa380502(v=vs.85).aspx

You should be able to start with my sspi/ntlm package and change some code to implement Kerberos. In fact I have (as far as I remember) implemented Negotiate provider (it is NTLM + Kerberos) in one of my projects, and it worked. I will try and cleanup my code and publish some code when I have free time. But you should have a go - it should not be hard.

Alex

**Comment by alexbrainman** [comment]
> I have (as far as I remember) implemented Negotiate provider (it is NTLM + Kerberos) in one of my projects, and it worked.

Here 05f0258 are my changes.

Alex

**Comment by enj** [comment]
Thanks I will try this out and let you know :smile:

**Comment by brunoqc** [comment]
@enj did you test it?

**Comment by enj** [comment]
@brunoqc I have a WIP PR https://github.com/openshift/origin/pull/11371

There are still some bugs to take care of in my code and in this library.  But for the most part everything works as expected.  This did not work with the `runas` command.

**Comment by trung** [comment]
When channel binding/extended protection for authentication ([here](https://tools.ietf.org/html/rfc5929#section-4) and [here](https://blogs.msdn.microsoft.com/openspecification/2013/03/26/ntlm-and-channel-binding-hash-aka-extended-protection-for-authentication/)) is enabled in the server. There needs an extra step to obtain server certificate and encode it in the input buffer before sending to `InitializeSecurityContext`. I copied the implementation from [Python Library](https://github.com/brandond/requests-negotiate-sspi/blob/master/requests_negotiate_sspi/requests_negotiate_sspi.py#L57) and made it work.

Will get an PR raise for review

**Comment by enj** [comment]
I am going to close this since it appears to be working for me (even with `runas`).  I will open issues or PRs if I encounter bugs after the code has seen more real world use.

openshift/origin#11371

**Comment by alexbrainman** [comment]
> I am going to close this since it appears to be working for me (even with runas).

Glad to hear that.

> I will open issues or PRs if I encounter bugs after the code has seen more real world use.

SGTM

Alex
