### ISSUE TITLE
HTTP Transport/RoundTripper?

### ISSUE THREAD

**Issue by sean-r-williams** [alexbrainman/sspi#14]
Hi all,

I'm trying to call an NTLM-authenticated HTTP service in Go. I'm running on a Windows host and the default user credentials accessible via SSPI have access to this service.

I've tried using the following related modules:
* [`Azure/go-ntlmssp`](https://github.com/Azure/go-ntlmssp): Provides a RoundTripper for NTLM auth, but appears to expect explicit credentials
* [`dpotapov/go-spnego`](https://github.com/dpotapov/go-spnego): Provides an SPNEGO RoundTripper (and depends on this package!), but appears to only support Kerberos itself (not NTLM)

I tried reading through the tests as described in [#6 (comment)](https://github.com/alexbrainman/sspi/issues/6#issuecomment-416755790), but I'm not well-versed in Go and didn't understand how to chain this into existing HTTP client calls. I have to provide an NTLMSSP_NEGOTIATE message to the server before getting an NTLMSSP_CHALLENGE, and I'm not sure how to build one of these using the methods provided in `sspi` or `sspi/negotiate`.

Is there some documentation available for using this package to do NTLM negotiation?

**Comment by alexbrainman** [comment]
> Is there some documentation available for using this package to do NTLM negotiation?

If you need to call a NTLM protected http server from Windows client, try this test

https://github.com/alexbrainman/sspi/blob/1a75b4708caa219fd8d8261cd37c923ff6710a32/ntlm/http_test.go#L121-L155

This is very old code that have not been tested for a long time. So I would not be surprised that it does not work.

Alex

**Comment by sean-r-williams** [comment]
Thanks for the context! I was able to write a RoundTripper based on this and [the one from `Azure/go-ntlmssp`](https://github.com/Azure/go-ntlmssp/blob/master/negotiator.go).
