### ISSUE TITLE
x509 certificates from cert store

### ISSUE THREAD

**Issue by tsaridas** [alexbrainman/sspi#2]
Hello,

I have been looking for a way to be able to use x509 certificates from the cert store and found a windows documentation that it can be done with schannel.

[Windows Documentaiton](https://msdn.microsoft.com/de-de/library/windows/desktop/aa378819%28v=vs.85%29.aspx)

Is there any chance this library can help with that ?

thnx

**Comment by alexbrainman** [comment]
> Is there any chance this library can help with that ?

This library uses schannel SSPI interface to to communicate with HTTPS web server. So it is client-side only and does not care about x509 certificates. All security is validated by schannel code itself. I suspect you could use it to build HTTPS server as well, but I have not done it yet.

I put very little time into this code, so there are many bugs here. Please do not use it unless you expect things to break.

Alex

**Comment by tsaridas** [comment]
I am trying to get the certificates stored in the windows cert store for the client side.

Im am not trying to get the server to accept client certificates but the client to forward the certificates which are stored in the certificate store.

AT

**Comment by alexbrainman** [comment]
> I am trying to get the certificates stored in the windows cert store for the client side.
> 
> Im am not trying to get the server to accept client certificates but the client to forward the certificates which are stored in the certificate store.

This package will not help you with that. Sorry.

Alex

**Comment by tsaridas** [comment]
thnx
