### ISSUE TITLE
Example implementation

### ISSUE THREAD

**Issue by tsraza** [alexbrainman/sspi#6]
Can you please provide an example implementation, perhaps in the readme.

**Comment by alexbrainman** [comment]
@tsraza my package is not ready for examples yet - many things are broken and have to be changed to make package useful for others. Sorry.

Alex

**Comment by enj** [comment]
openshift/origin#11371 uses the negotiate package (everything appears to be working).

**Comment by tsraza** [comment]
Found some working examples:

* client: https://github.com/bhendo/sspi-client
* server: https://github.com/nycmonkey/authenticator
